# Generated by Django 5.0.4 on 2024-06-18 00:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userperson',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userperson',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='userperson',
            unique_together={('user', 'person')},
        ),
    ]
