# Generated by Django 5.0.4 on 2024-06-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_userperson_note_userperson_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperson',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userperson',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
