# Generated by Django 5.0.4 on 2024-06-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_alter_userperson_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperson',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
