# Generated by Django 5.0.4 on 2024-06-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_alter_userperson_note_alter_userperson_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperson',
            name='note',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
